name: Test and coverage
on:
  push:
    branches:
      - master

jobs:
  test-and-cover:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: installation 🏗
        run: npm install
      - name: test 🔬🧪
        run: npm run test:coverage
      - name: coverage info directory
        run: mkdir coverage
      - name: Coverage ☔
        run: npm run get:coverage > coverage/lcov.info
      - name: Delete nyc output
        run: rm -r .nyc_output
      - name: Publish in Coveralls ⭐
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete coverage output
        run: rm -r coverage